- uses: keithweaver/aws-s3-github-action@v1.0.0
  with:
    command: cp
    source: /site/*
    destination: s3://www.killingklovis.com
    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws_region: us-west-2
